In [2]:
import pandas as pd

data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headphones"],
    "Category": ["Electronics", "Accessories", "Accessories", "Electronics", "Accessories"],
    "Price": [1200, 25, 75, 300, None],
    "Stock": [15, 120, 45, 30, 80]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

      Product     Category   Price  Stock
0      Laptop  Electronics  1200.0     15
1       Mouse  Accessories    25.0    120
2    Keyboard  Accessories    75.0     45
3     Monitor  Electronics   300.0     30
4  Headphones  Accessories     NaN     80

In [5]:
# Inspect & filter

mask = (df["Category"] == "Electronics") & (df["Stock"] > 3)
df[mask]

   Product     Category   Price  Stock
0   Laptop  Electronics  1200.0     15
3  Monitor  Electronics   300.0     30

In [6]:
# Handle missing data
df["Price"] = df["Price"].fillna(50.0)
df

      Product     Category   Price  Stock
0      Laptop  Electronics  1200.0     15
1       Mouse  Accessories    25.0    120
2    Keyboard  Accessories    75.0     45
3     Monitor  Electronics   300.0     30
4  Headphones  Accessories    50.0     80

In [7]:
# Calculate the total sum Stock available for each category
# Aggregation

total_stock_by_category = df.groupby("Category")["Stock"].sum()
total_stock_by_category

Category
Accessories    245
Electronics     45
Name: Stock, dtype: int64

In [8]:
# Sorting

sorted_df = df.sort_values(by="Price", ascending=False)
sorted_df

      Product     Category   Price  Stock
0      Laptop  Electronics  1200.0     15
3     Monitor  Electronics   300.0     30
2    Keyboard  Accessories    75.0     45
4  Headphones  Accessories    50.0     80
1       Mouse  Accessories    25.0    120